version = 0.1

[dev.deploy.parameters]
region = "us-east-1"
confirm_changeset = false
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
stack_name = "showcase-api-dev"
resolve_s3 = true
s3_prefix = "showcase-api-dev"
parameter_overrides = "Environment=dev ClientAppUrl=\"https://develop.dwi87gyskj43z.amplifyapp.com\""
disable_rollback = true

[prod.deploy.parameters]
region = "us-east-1"
confirm_changeset = true
fail_on_empty_changeset = false
capabilities = "CAPABILITY_IAM"
stack_name = "showcase-api-prod"
resolve_s3 = true
s3_prefix = "showcase-api-prod"
parameter_overrides = "Environment=prod ClientAppUrl=\"https://main.dwi87gyskj43z.amplifyapp.com\""
