AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64
    Timeout: 15
    MemorySize: 256
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ENVIRONMENT: !Ref Environment

Resources:
  GraphqlApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub showcase-api-${Environment}
      Handler: handler.handler
      CodeUri: ../dist/apps/api
      Events:
        HttpApi:
          Type: HttpApi
          Properties:
            Path: /graphql
            Method: POST

Outputs:
  ApiEndpoint:
    Description: GraphQL API endpoint URL
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/graphql
