AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod
  ClientAppUrl:
    Type: String
    Description: 'The allowed origin for CORS'


Globals:
  Function:
    Runtime: nodejs24.x
    Architectures:
      - arm64
    Timeout: 15
    MemorySize: 256
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ENVIRONMENT: !Ref Environment

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowOrigins:
          - !Ref ClientAppUrl
        AllowMethods:
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        AllowCredentials: true

  GraphqlApi:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub showcase-api-${Environment}
      Handler: handler.handler
      CodeUri: ../dist/apps/api
      Environment:
        Variables:
          CLIENT_APP_URL: !Ref ClientAppUrl
      Events:
        GraphqlPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /graphql
            Method: POST
        GraphqlOptions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /graphql
            Method: OPTIONS

Outputs:
  ApiEndpoint:
    Description: GraphQL API endpoint URL
    Value: !Sub https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com/graphql
